# -*- coding: utf-8 -*-
"""백준설탕배달.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HpAQhI80dlVoXyJyU-6zKHwUTks9ulhv
"""

sugar = int(input())

bag = 0

while sugar >= 0 :
    if sugar % 5 == 0 :
      bag += (sugar // 5)
      print(bag)
      break
    s11ugar -= 3
    bag += 1
else :
	print(-1)

